Traceback (most recent call last):
  File "C:\Users\likyb\AppData\Local\Programs\Python\Python38\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\likyb\AppData\Local\Programs\Python\Python38\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\likyb\AppData\Local\Programs\Python\Python38\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\likyb\AppData\Local\Programs\Python\Python38\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\likyb\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\likyb\AppData\Local\Programs\Python\Python38\lib\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "C:\Users\likyb\AppData\Local\Programs\Python\Python38\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\likyb\AppData\Local\Programs\Python\Python38\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print(classification_report(y_test, pred_dummy, target_names=["not nine", "nine"]))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_27356/3189847149.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mprint[0m[1;33m([0m[0mclassification_report[0m[1;33m([0m[0my_test[0m[1;33m,[0m [0mpred_dummy[0m[1;33m,[0m [0mtarget_names[0m[1;33m=[0m[1;33m[[0m[1;34m"not nine"[0m[1;33m,[0m [1;34m"nine"[0m[1;33m][0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mNameError[0m: name 'pred_dummy' is not defined
NameError: name 'pred_dummy' is not defined

